gatos/urls.py
from django.urls import path

from . import views

app_name = 'gatos'
urlpatterns = [
    path('', views.GatoListView.as_view(), name='index'),
    path('create/', views.GatoCreateView.as_view(), name='create'),
    path('<int:pk>/', views.GatoDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.GatoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.GatoDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/<int:pk>/', views.SinglecategoryDetailView.as_view(), name='singlecategory'),
]

gatosite2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('gatos/', include('gatos.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('fotos/', views.fotos, name='fotos'),
    path('', views.index, name='index'),
]

gatos/models.py
from django.db import models
from django.conf import settings
from datetime import datetime  
from django.urls import reverse


class Post(models.Model):
    name = models.CharField(max_length=255)
    caracteristica = models.CharField(max_length=255)
    imagem = models.URLField(max_length=200, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return f'{self.name}'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True)
    
    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

gatos/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'caracteristica',
            'imagem',
        ]
        labels = {
            'name': 'Título',
            'caracteristica': 'Caracteristica',
            'imagem': 'URL da imagem',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

gatos/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm

class GatoDetailView(generic.DetailView):
    model = Post
    template_name = 'gatos/detail.html'


class GatoListView(generic.ListView):
    model = Post
    template_name = 'gatos/index.html'


class GatoCreateView(generic.CreateView):
    model = Post
    fields = ['name', 'caracteristica', 'imagem']
    template_name = 'gatos/create.html'
    success_url = '/gatos'


class GatoUpdateView(generic.UpdateView):
    model = Post
    fields = ['name', 'caracteristica', 'imagem']
    template_name = 'gatos/update.html'
    success_url = '/gatos'


class GatoDeleteView(generic.DeleteView):
    model = Post
    template_name = 'gatos/delete.html'
    success_url = '/gatos'


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('gatos:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'gatos/comment.html', context)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'gatos/category.html'


class SinglecategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'gatos/singlecategory.html'

staticpages/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)


def fotos(request):
    context = {}
    return render(request, 'staticpages/fotos.html', context)

gatos/templates/gatos/category.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de gatos</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        
        <h3><a href="{% url 'gatos:singlecategory' category.id %}" class="voltar">{{category.name}}</a></h3>
        
        <p> - {{category.description}}</p>
        <div class="container-1">
            {% for post in category.posts.all %}
                <div class="child-2">
                    <a href="{% url 'gatos:detail' post.id %}" class="fotos"><p>{{ post.name }}</p></a>

                </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

</section>

{% endblock content %}

gatos/templates/gatos/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Adicione seu comentário ao post {{ post.name }}</h2>

<form action="{% url 'gatos:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>
<br>
<div class="container-1">
    <div class="child-1">
        <a href="{% url 'gatos:detail' post.id %}" class="fotos">Voltar para a página do post</a>
    </div>
</div>

{% endblock content %}

gatos/templates/gatos/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Gato</h2>
<form method="POST" action="{% url 'gatos:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

gatos/templates/gatos/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'gatos:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o gato "{{ post.name }}"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

gatos/templates/gatos/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }}
{% endblock title %}

{% block content %}
<h2> {{ post.name }} </h2>

<div class="container-2">
    <div class="child-1">
        <img src="{{ post.imagem }}" alt="Foto do {{ post.name}}" style="max-width: 300px;">
    </div>
    <div class="child-1">
        <p>Esse é o gato mais {{ post.caracteristica }} da internet</p>
    </div>
    <div class="child-1">
        <p>Postado em {{ post.date }}</p>
        <br>
        <hr>
        <br>
        
        {% if post.category_set.all %}

        Incluso nas categorias:
        <div class="container-2">
            
            {% for category in post.category_set.all %}
            <div class="child-1">
            <a href="{% url 'gatos:singlecategory' category.id %}" class="voltar">{{category.name}}</a>
            </div>
            {% endfor %}
            {% endif %}
        </div>

    </div>
    
</div>
<br>
<div class="container-1">
    <div class="child-1">
        
            <a href="{% url 'gatos:update' post.id %}" class="fotos">Editar</a>
            <a href="{% url 'gatos:delete' post.id %}" class="fotos">Apagar</a>
        
    </div>
</div>
<br>


    
    <section>
        <h3>Comentários</h3>
        <div class="container-2">
            <ul>

                {% if post.comment_set.all %}
                    {% for comment in post.comment_set.all reversed %}
                    <figure>
                        <blockquote>
                            "{{ comment.text }}"
                        </blockquote>
                        <figcaption> {{ comment.author }}
                        
                        <p>Postado em {{ comment.date }}</p>
                        <hr>
                    </figure>
                    {% endfor %}
                {% else %}
                <p>Não há comentários ainda.</p>
                {% endif %}
            </ul>
        </div>
        <br>
        <div class="container-1">
            <div class="child-1">
                <a href="{% url 'gatos:comment' post.pk %}" class="fotos">Comente</a>
            </div>
        </div>
    </section>

<br>
<br>
<a href="{% url 'gatos:index'  %}" class="voltar">Voltar</a>
{% endblock content %}

gatos/templates/gatos/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os gatos</h2>

<section class="container-1">
    <div class=child-1>
        <a href="{% url 'gatos:create' %}" class="fotos">Adicionar Novo Gato</a>
    </div>
</section>

<br>

{% if post_list %}
<section class="container-1">
    {% for post in post_list %}
    <div class="child-2">
        <a href="{% url 'gatos:detail' post.id %}" class="fotos"><p>{{ post.name }}</p></a>
        
    </div>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum gato.</p>
{% endif %}



{% endblock content %}

gatos/templates/gatos/singlecategory.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>{{ category.name }}</h2>
<p> - {{category.description}}</p>

<section>
    
    <article>
        
        
        <div class="container-1">
            {% for post in category.posts.all %}
                <div class="child-2">
                    <a href="{% url 'gatos:detail' post.id %}" class="fotos"><p>{{ post.name }}</p></a>

                </div>
            {% endfor %}
        </div>
    </article>
    

</section>


{% endblock content %}

gatos/templates/gatos/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do {{ post.name }}</h2>
<form method="POST" action="{% url 'gatos:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %}

<!DOCTYPE html><html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="icon" href="{% static 'paw2.png' %}" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400&display=swap" rel="stylesheet"> 

    <title>
        {% block title %}{% endblock %} | Gatos
    </title>
</head>

<body>
    <header>
        
        <a href="{% url 'index' %}"> <img src="{% static 'gato_vingativo.jpg' %}"> </a>
        <div class="container-5">
            <h1>Melhores gatos da internet</h1>
        </div>
        <a href="{% url 'index' %}"> <img src="{% static 'gato_vingativo.jpg' %}"> </a>
    </header>
    <nav>
        <a href="{% url 'index' %}">Home</a>
        <a href="{% url 'about' %}">Sobre</a>
        <a href="{% url 'gatos:index' %}">Fotos</a>
        <a href="{% url 'gatos:category' %}">Categorias</a>
    </nav>

    <main>
        {% block content %}
        {% endblock content %}
    </main>

    <footer>
        <p>Copyright - 2021 - Roberto Sobral</p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>


<p>Esse site tem a importante missão de educar toda população sobre a necessidade de se conhecer boas fotos de gatos.</p>
<p>Pode-se dizer que somos um acervo, ou uma enciclopédia, mas preferimos nos referir como: "a garantia de um futuro para a humanidade".</p>

<br>
<br>

<div class="container-4">
    <p>Percebo que você está em uma tela pequena</p>
</div>



{% endblock content %}

staticpages/templates/staticpages/fotos.html
{% extends 'base.html' %}

{% block title %}
Fotos
{% endblock title %}

{% block content %}

{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h2>Bem vindo ao maior site de fotos de gatos da USP</h2>

<p>O que você espera encontrar?</p>
<ul>
    <li>Quais são as novidades no mundo das fotos de gatos?</li>
    <li>Quais são as trends no mundo das fotos de gatos?</li>
</ul>

<h4>Isso você não encontra aqui, pois nós só trabalhamos com as fotos clássicas</h4>

<br>
<br>

<div class="container-4">
    <p>Percebo que você está em uma tela pequena</p>
</div>

{% endblock content %}